spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456@aA
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true

  jpa:
    show-sql: true

  jackson:
    default-property-inclusion: non_null
  redis:
    host: localhost
    port: 6379

server:
  servlet:
    context-path: /sell
  port: 80